# Generated by Django 6.1 on 2026-08-19 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geofencing', '0001_initial'),
        ('tourists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_level', models.CharField(choices=[('INFO', 'General Advisory / Advisory'), ('WARNING', 'Severe Weather / High Hazard Warning'), ('CRITICAL', 'Critical Emergency / Immediate Action Required')], default='WARNING', max_length=20)),
                ('target_type', models.CharField(choices=[('ALL_TOURISTS', 'All Active Tourists in Region'), ('GEO_RADIUS', 'Tourists within Geo-Radius'), ('GEO_ZONE', 'Tourists inside Specific Geofence Zone')], default='ALL_TOURISTS', max_length=20)),
                ('center_lat', models.FloatField(blank=True, null=True)),
                ('center_lng', models.FloatField(blank=True, null=True)),
                ('radius_meters', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geofencing.geozone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_receipts', to='tourists.touristprofile')),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='alerts.emergencybroadcast')),
            ],
            options={
                'unique_together': {('broadcast', 'tourist')},
            },
        ),
    ]
