# Generated by Django 6.1 on 2026-08-19 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('geofencing', '0002_geofencebreachlog_authority_notified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertreceipt',
            options={'ordering': ['-delivered_at']},
        ),
        migrations.RenameField(
            model_name='emergencybroadcast',
            old_name='center_lat',
            new_name='center_latitude',
        ),
        migrations.RenameField(
            model_name='emergencybroadcast',
            old_name='center_lng',
            new_name='center_longitude',
        ),
        migrations.RemoveField(
            model_name='emergencybroadcast',
            name='alert_level',
        ),
        migrations.AddField(
            model_name='emergencybroadcast',
            name='alert_type',
            field=models.CharField(choices=[('DISASTER', 'Natural Disaster (Evacuation / Surge)'), ('SEVERE_WEATHER', 'Severe Weather / High Waves Warning'), ('CRIME_ACTIVITY', 'Crime Activity / Heightened Vigilance'), ('ACCIDENT', 'Traffic Collision / Road Obstruction'), ('CROWD_EMERGENCY', 'Crowd Emergency / Stampede Risk'), ('RESTRICTED_AREA', 'Restricted Perimeter / Prohibited Zone'), ('GENERAL_SAFETY', 'General Safety Advisory')], default='GENERAL_SAFETY', max_length=30),
        ),
        migrations.AddField(
            model_name='emergencybroadcast',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical Emergency (Immediate Action Required)'), ('WARNING', 'Warning (Heightened Vigilance)'), ('ADVISORY', 'Advisory (General Information)')], default='WARNING', max_length=20),
        ),
        migrations.AddField(
            model_name='emergencybroadcast',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emergencybroadcast',
            name='message',
            field=models.TextField(help_text='Detailed safety advisory and instructions for tourists'),
        ),
        migrations.AlterField(
            model_name='emergencybroadcast',
            name='radius_meters',
            field=models.IntegerField(blank=True, help_text='Impact radius in meters', null=True),
        ),
        migrations.AlterField(
            model_name='emergencybroadcast',
            name='target_type',
            field=models.CharField(choices=[('ALL_TOURISTS', 'All Active Tourists in Region'), ('ZONE_SPECIFIC', 'Tourists inside Specific Geofence Zone'), ('GEO_RADIUS', 'Tourists within Geographic Radius')], default='ALL_TOURISTS', max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencybroadcast',
            name='target_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='geofencing.geozone'),
        ),
    ]
