# Generated by Django 6.1 on 2026-08-19 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponderUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('agency', models.CharField(choices=[('POLICE', 'Police Patrol / PCR Van'), ('TOURISM_POLICE', 'Tourism Police Task Force'), ('AMBULANCE', '108 Ambulance / Medical EMS'), ('FIRE_RESCUE', 'Fire & Disaster Rescue'), ('BEACH_LIFEGUARD', 'Coast Guard / Beach Lifeguards')], default='POLICE', max_length=30)),
                ('callsign', models.CharField(help_text='e.g. PCR-PANJIM-04, LIFEGUARD-CALANGUTE', max_length=100)),
                ('officer_in_charge', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available / On Patrol'), ('DISPATCHED', 'Dispatched / En Route'), ('ON_SCENE', 'On Scene / Engaged'), ('OFF_DUTY', 'Off Duty / Inactive')], default='AVAILABLE', max_length=20)),
                ('current_latitude', models.FloatField()),
                ('current_longitude', models.FloatField()),
                ('station_base_name', models.CharField(blank=True, max_length=150)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sos_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active SOS Emergency'), ('ACKNOWLEDGED', 'Operator Acknowledged'), ('DISPATCHED', 'Responders Dispatched'), ('ON_SCENE', 'Responders On Scene'), ('RESOLVED', 'Resolved & Safe'), ('CANCELLED', 'Cancelled by User / False Alarm')], default='ACTIVE', max_length=20)),
                ('trigger_type', models.CharField(choices=[('MANUAL_BUTTON', 'SOS Panic Button Tap'), ('COUNTDOWN_TRIGGER', 'Countdown Timer Expired'), ('SILENT_SOS', 'Silent SOS (Triple Tap)'), ('GEOFENCE_AUTOPANIC', 'Auto Geofence Breach Alarm'), ('FALL_DETECT', 'Fall / Impact Motion Sensor'), ('VOICE_KEYWORD', 'Voice Emergency Keyword')], default='MANUAL_BUTTON', max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_accuracy', models.FloatField(default=5.0)),
                ('battery_level', models.IntegerField(default=100)),
                ('location_address', models.CharField(blank=True, max_length=255)),
                ('emergency_notes', models.TextField(blank=True)),
                ('audio_snapshot', models.FileField(blank=True, null=True, upload_to='sos_audio/')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='tourists.touristprofile')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('eta_minutes', models.IntegerField(default=6)),
                ('dispatch_status', models.CharField(choices=[('ASSIGNED', 'Assigned & Alerted'), ('EN_ROUTE', 'En Route to Scene'), ('ARRIVED', 'Arrived on Scene'), ('COMPLETED', 'Mission Completed')], default='ASSIGNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='emergency.responderunit')),
                ('sos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='emergency.sosalert')),
            ],
            options={
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSLiveBreadcrumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0.0)),
                ('battery_level', models.IntegerField(default=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('sos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breadcrumbs', to='emergency.sosalert')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
