# Generated by Django 6.1 on 2026-08-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosdispatch',
            options={},
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active SOS Emergency'), ('ACKNOWLEDGED', 'Operator Acknowledged'), ('RESPONDING', 'Responders En Route / Responding'), ('RESOLVED', 'Resolved & Safe'), ('CANCELLED', 'Cancelled by User / False Alarm')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='sosdispatch',
            name='eta_minutes',
            field=models.IntegerField(default=8),
        ),
    ]
