# Generated by Django 6.1 on 2026-08-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TOURIST', 'Tourist'), ('AUTHORITY', 'Law Enforcement / Authority Officer'), ('OPERATOR', 'Authority C2 Operator'), ('RESPONDER', 'Emergency Field Responder'), ('ADMIN', 'Tourism Administrator')], default='TOURIST', max_length=20),
        ),
    ]
