# Generated by Django 6.1 on 2026-08-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafeRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('origin_name', models.CharField(max_length=150)),
                ('destination_name', models.CharField(max_length=150)),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('waypoints_geojson', models.JSONField(help_text='Array of [lat, lng] coordinates along the safe corridor')),
                ('safety_score', models.IntegerField(default=90, help_text='Safety Index score (0-100)')),
                ('lighting_rating', models.CharField(choices=[('WELL_LIT', 'Continuous Street Lighting'), ('MODERATE_LIT', 'Partial Lighting'), ('POORLY_LIT', 'Dim / Poor Lighting')], default='WELL_LIT', max_length=30)),
                ('patrol_frequency', models.CharField(default='Regular Police Patrol (every 15 min)', max_length=100)),
                ('distance_km', models.FloatField(default=2.5)),
                ('estimated_minutes', models.IntegerField(default=25)),
                ('active_safeguards', models.TextField(blank=True, help_text='e.g. CCTV coverage, 2 Police Kiosks, 24x7 Open Stores')),
                ('is_verified', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyPOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('poi_type', models.CharField(choices=[('POLICE', 'Police Station / Outpost'), ('TOURIST_POLICE', 'Tourist Police Assistance Booth'), ('HOSPITAL', 'Hospital / Emergency Care'), ('TOURIST_KIOSK', 'Official Tourist Helpdesk & Kiosk'), ('SAFE_SHELTER', 'Designated Safe Haven / Shelter'), ('EMBASSY', 'Consulate / Foreign Mission'), ('BEACH_TOWER', 'Lifeguard Watchtower')], default='POLICE', max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('is_24_hours', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
