# Generated by Django 6.1 on 2026-08-19 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('zone_type', models.CharField(choices=[('SAFE_HAVEN', 'Safe Haven / High Security Zone'), ('CAUTION', 'Caution Zone / High Alert'), ('HIGH_RISK', 'High Risk Hazard Zone'), ('RESTRICTED', 'Restricted Area / No Entry'), ('CURFEW', 'Night Curfew Zone')], default='CAUTION', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('polygon_geojson', models.JSONField(help_text='GeoJSON Polygon geometry with coordinates array')),
                ('center_latitude', models.FloatField()),
                ('center_longitude', models.FloatField()),
                ('radius_meters', models.IntegerField(default=500, help_text='Approximate radius in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('curfew_start_time', models.TimeField(blank=True, null=True)),
                ('curfew_end_time', models.TimeField(blank=True, null=True)),
                ('max_crowd_threshold', models.IntegerField(default=500)),
                ('safety_advisory', models.TextField(blank=True, help_text='Safety warning delivered to tourists when entering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeofenceBreachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breach_type', models.CharField(choices=[('ENTER_RESTRICTED', 'Entered Restricted Zone'), ('ENTER_DANGER', 'Entered Danger Zone'), ('CURFEW_VIOLATION', 'Curfew Hours Violation'), ('EXTENDED_DWELL', 'Extended Inactivity in Risk Zone')], max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('action_taken', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_logs', to='tourists.touristprofile')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaches', to='geofencing.geozone')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
