# Generated by Django 6.1 on 2026-08-19 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofencing', '0001_initial'),
        ('tourists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofencebreachlog',
            name='authority_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geofencebreachlog',
            name='risk_score_after',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='geofencebreachlog',
            name='breach_type',
            field=models.CharField(choices=[('ENTRY_SAFE', 'Entered Safe Haven Zone'), ('ENTRY_CAUTION', 'Entered Caution Zone'), ('ENTER_RESTRICTED', 'Entered Restricted Zone'), ('ENTER_DANGER', 'Entered High-Risk Hazard Zone'), ('ENTER_EMERGENCY', 'Entered Emergency Evacuation Zone'), ('CURFEW_VIOLATION', 'Curfew Hours Violation'), ('ZONE_EXIT', 'Exited Geofence Zone')], max_length=30),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='zone_type',
            field=models.CharField(choices=[('SAFE', 'Safe Zone / Designated Haven'), ('CAUTION', 'Caution Zone / Heightened Vigilance'), ('HIGH_RISK', 'High Risk Hazard Zone'), ('RESTRICTED', 'Restricted Area / No Entry'), ('EMERGENCY', 'Emergency Disaster Evacuation Zone')], default='CAUTION', max_length=30),
        ),
        migrations.CreateModel(
            name='TouristZonePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('last_detected_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_dispatched', models.BooleanField(default=True)),
                ('authority_notified', models.BooleanField(default=False)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_zone_presences', to='tourists.touristprofile')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_occupants', to='geofencing.geozone')),
            ],
            options={
                'indexes': [models.Index(fields=['tourist', 'zone', 'is_active'], name='geofencing__tourist_22c36a_idx')],
            },
        ),
    ]
