# Generated by Django 6.1 on 2026-08-19 13:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('id_document_type', models.CharField(default='Aadhaar', help_text='e.g. Passport, Aadhaar, National ID', max_length=50)),
                ('id_document_hash', models.CharField(blank=True, help_text='SHA-256 hash of document for privacy verification', max_length=128)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('medical_conditions', models.TextField(blank=True, help_text='Pre-existing conditions, cardiac history, etc.')),
                ('allergies', models.TextField(blank=True, help_text='Medication/food allergies')),
                ('hotel_stay_details', models.CharField(blank=True, max_length=255)),
                ('destination_city', models.CharField(default='Goa, India', max_length=100)),
                ('trip_start_date', models.DateField(blank=True, null=True)),
                ('trip_end_date', models.DateField(blank=True, null=True)),
                ('trip_status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active Trip'), ('COMPLETED', 'Completed'), ('SOS_ACTIVE', 'SOS Emergency Active')], default='ACTIVE', max_length=20)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('last_location_time', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.IntegerField(default=95, help_text='Battery percentage (0-100)')),
                ('is_live_tracking_enabled', models.BooleanField(default=True)),
                ('safe_checkin_interval_mins', models.IntegerField(default=120)),
                ('last_safe_checkin', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TouristLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0.0, help_text='Speed in km/h')),
                ('battery_level', models.IntegerField(default=100)),
                ('accuracy', models.FloatField(default=5.0, help_text='GPS accuracy in meters')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='tourists.touristprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
