# Generated by Django 6.1 on 2026-08-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTouristID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('crypto_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Verified & Active'), ('FLAGGED', 'Security Watchlist / Flagged'), ('SUSPENDED', 'Temporarily Suspended'), ('EXPIRED', 'Expired Validity')], default='ACTIVE', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('verification_token_secret', models.CharField(max_length=64)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('tourist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_id', to='tourists.touristprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IDVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier_name', models.CharField(help_text='Officer or Scanner operator name', max_length=150)),
                ('verifier_role', models.CharField(default='Tourism Police', max_length=50)),
                ('verifier_badge', models.CharField(blank=True, max_length=50)),
                ('location_name', models.CharField(default='Checkpoint Alpha', max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status_result', models.CharField(default='VALID', max_length=30)),
                ('verification_notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('digital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='digital_id.digitaltouristid')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
