# Generated by Django 6.1 on 2026-08-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blackspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('THEFT_PRONE', 'High Theft / Snatching Zone'), ('ISOLATED_UNLIT', 'Isolated / Unlit Night Stretch'), ('ACCIDENT_PRONE', 'Accident & Collision Blackspot'), ('WATER_HAZARD', 'Dangerous Waters / Rip Current Zone'), ('SCAM_CONCENTRATION', 'Tourist Scam / Tout Concentration'), ('RUGGED_CLIFF', 'Treacherous Cliff / Slip Hazard')], max_length=50)),
                ('risk_weight', models.IntegerField(default=75, help_text='Risk factor severity (1-100)')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_meters', models.IntegerField(default=300)),
                ('incident_count_30d', models.IntegerField(default=8)),
                ('safety_advice', models.TextField(help_text='Actionable advice for tourists venturing nearby')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TouristRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=15, help_text='Overall composite risk index (0-100)')),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe / Minimal Risk (0-25)'), ('MODERATE', 'Moderate Risk (26-50)'), ('HIGH', 'High Risk (51-75)'), ('CRITICAL', 'Critical Danger (76-100)')], default='SAFE', max_length=20)),
                ('spatial_risk_score', models.IntegerField(default=10, help_text='Proximity to blackspots and high risk zones')),
                ('temporal_risk_score', models.IntegerField(default=10, help_text='Late night / isolated hours factor')),
                ('isolation_risk_score', models.IntegerField(default=10, help_text='Distance from police booths and safe havens')),
                ('crowd_risk_score', models.IntegerField(default=10, help_text='Crowd anomaly or stampede factor')),
                ('device_health_score', models.IntegerField(default=5, help_text='Battery depletion or communication loss risk')),
                ('primary_risk_factor', models.CharField(blank=True, max_length=255)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='tourists.touristprofile')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
