# Generated by Django 6.1 on 2026-08-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristriskassessment',
            name='crowd_risk_score',
            field=models.IntegerField(default=10, help_text='Disaster alerts & geofences (0-15)'),
        ),
        migrations.AlterField(
            model_name='touristriskassessment',
            name='device_health_score',
            field=models.IntegerField(default=5, help_text='Battery depletion risk (0-10)'),
        ),
        migrations.AlterField(
            model_name='touristriskassessment',
            name='isolation_risk_score',
            field=models.IntegerField(default=10, help_text='Distance from police booths and safe havens (0-20)'),
        ),
        migrations.AlterField(
            model_name='touristriskassessment',
            name='risk_level',
            field=models.CharField(choices=[('SAFE', 'Safe (0–30)'), ('MODERATE', 'Moderate (31–60)'), ('HIGH', 'High (61–80)'), ('CRITICAL', 'Critical (81–100)')], default='SAFE', max_length=20),
        ),
        migrations.AlterField(
            model_name='touristriskassessment',
            name='spatial_risk_score',
            field=models.IntegerField(default=10, help_text='Proximity to blackspots and high risk zones (0-35)'),
        ),
        migrations.AlterField(
            model_name='touristriskassessment',
            name='temporal_risk_score',
            field=models.IntegerField(default=10, help_text='Late night / isolated hours factor (0-25)'),
        ),
    ]
