# Generated by Django 6.1 on 2026-08-19 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('reporter_name', models.CharField(blank=True, max_length=150)),
                ('reporter_phone', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('HARASSMENT', 'Harassment / Eve Teasing'), ('THEFT', 'Theft / Snatching'), ('ACCIDENT', 'Road / Traffic Accident'), ('MEDICAL', 'Medical / Cardiac Emergency'), ('LOST_PERSON', 'Lost Tourist / Missing Person'), ('SCAM_FRAUD', 'Tourist Scam / Overcharging'), ('NATURAL_HAZARD', 'Landslide / Drowning / Hazard'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity / Crowd Anomaly'), ('OTHER', 'General Incident')], default='OTHER', max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical / Life Threatening')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported / Pending Triage'), ('VERIFIED', 'Verified / Triage Complete'), ('DISPATCHED', 'Responder Unit Dispatched'), ('INVESTIGATING', 'On-Scene Investigation'), ('RESOLVED', 'Resolved & Closed'), ('FALSE_ALARM', 'False Alarm / Dismissed')], default='REPORTED', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_name', models.CharField(blank=True, help_text='e.g. Baga Beach Shack #4, Panaji Promenade', max_length=255)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='incidents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='emergency.responderunit')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('note', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='incidents.incident')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
