# Generated by Django 6.1 on 2026-08-19 14:20

import incidents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('ACCIDENT', 'Accident / Collision'), ('CRIME', 'Crime / Theft / Assault'), ('HARASSMENT', 'Harassment / Eve Teasing'), ('MEDICAL', 'Medical Emergency'), ('LOST_PERSON', 'Lost Tourist / Missing Person'), ('LOST_PROPERTY', 'Lost Property / Valuables'), ('NATURAL_DISASTER', 'Natural Disaster / Flood / Landslide'), ('UNSAFE_AREA', 'Unsafe Area / Broken Streetlights / Hazard'), ('OTHER', 'Other / General Incident')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='evidence_image',
            field=models.FileField(blank=True, null=True, upload_to='incidents/', validators=[incidents.models.validate_incident_media]),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported / Pending Review'), ('VERIFIED', 'Verified / Triage Complete'), ('ASSIGNED', 'Assigned to Responder Unit'), ('IN_PROGRESS', 'Investigation / Response In Progress'), ('RESOLVED', 'Resolved & Closed'), ('REJECTED', 'Rejected / False Alarm')], default='REPORTED', max_length=20),
        ),
    ]
