# Generated by Django 6.1 on 2026-08-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisionCameraFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_code', models.CharField(max_length=50, unique=True)),
                ('location_name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stream_url', models.CharField(blank=True, help_text='RTSP or live simulated video feed stream URL', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('max_safe_capacity', models.IntegerField(default=120, help_text='Maximum safe tourist capacity in this camera sector')),
                ('sample_frame', models.ImageField(blank=True, null=True, upload_to='cctv_samples/')),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisionDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crowd_count', models.IntegerField(default=0)),
                ('density_tier', models.CharField(choices=[('LOW', 'Low Density (Safe)'), ('NORMAL', 'Optimal Density'), ('CROWDED', 'High Density (Advisory)'), ('STAMPEDE_RISK', 'Critical Surge / Stampede Hazard')], default='NORMAL', max_length=20)),
                ('anomaly_detected', models.CharField(choices=[('NONE', 'Normal Activity'), ('CROWD_SURGE', 'Sudden Crowd Surge / Stampede Precursor'), ('VIOLENCE_FIGHT', 'Physical Violence / Brawl Detected'), ('VEHICLE_ACCIDENT', 'Vehicle Collision / Crash Detected'), ('RESTRICTED_BREACH', 'Perimeter Breach Detected')], default='NONE', max_length=30)),
                ('confidence_score', models.FloatField(default=0.92)),
                ('annotated_frame', models.ImageField(blank=True, null=True, upload_to='ai_frames/')),
                ('alert_dispatched', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='ai_services.visioncamerafeed')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
