# Generated by Django 6.1 on 2026-08-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
        ('geofencing', '0002_geofencebreachlog_authority_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visioncamerafeed',
            name='coverage_area_sqm',
            field=models.FloatField(default=250.0, help_text='Camera field-of-view physical coverage area in square meters'),
        ),
        migrations.AddField(
            model_name='visioncamerafeed',
            name='critical_threshold_count',
            field=models.IntegerField(default=100, help_text='Threshold count that triggers automated congestion alert'),
        ),
        migrations.AddField(
            model_name='visioncamerafeed',
            name='surge_threshold_rate',
            field=models.IntegerField(default=25, help_text='Rate of increase (people/min) that triggers surge alarm'),
        ),
        migrations.AddField(
            model_name='visioncamerafeed',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Associated geographic safety zone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_feeds', to='geofencing.geozone'),
        ),
        migrations.AddField(
            model_name='visiondetectionlog',
            name='concentration_index',
            field=models.FloatField(default=0.0, help_text='Spatial bottleneck concentration index (0.0 - 1.0)'),
        ),
        migrations.AddField(
            model_name='visiondetectionlog',
            name='crowd_density_score',
            field=models.FloatField(default=0.0, help_text='Normalized 0-100 crowd density index'),
        ),
        migrations.AddField(
            model_name='visiondetectionlog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visiondetectionlog',
            name='people_per_sqm',
            field=models.FloatField(default=0.0, help_text='Estimated people density per square meter'),
        ),
        migrations.AddField(
            model_name='visiondetectionlog',
            name='surge_rate_per_min',
            field=models.FloatField(default=0.0, help_text='Crowd rate of change in people per minute'),
        ),
        migrations.AlterField(
            model_name='visioncamerafeed',
            name='camera_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='visioncamerafeed',
            name='stream_url',
            field=models.CharField(blank=True, help_text='RTSP or live video stream URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='visiondetectionlog',
            name='anomaly_detected',
            field=models.CharField(choices=[('NONE', 'Normal Flow'), ('CROWD_SURGE', 'Sudden Crowd Surge / Influx'), ('ABNORMAL_CONCENTRATION', 'Abnormal Spatial Concentration / Bottleneck'), ('OVERCROWDING', 'Severe Capacity Exceeded')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='visiondetectionlog',
            name='density_tier',
            field=models.CharField(choices=[('LOW', 'Low Density (Safe)'), ('NORMAL', 'Optimal Density'), ('HIGH', 'High Density (Advisory)'), ('CRITICAL_SURGE', 'Critical Surge / Stampede Hazard')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='visiondetectionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
